package model;
// default package
// Generated Feb 25, 2015 11:58:03 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Donation generated by hbm2java
 */
public class Donation implements java.io.Serializable {

	private Integer donationId;
	private BigDecimal amount;
	private Person person;

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Donation() {
	}

	public Donation(Person person, BigDecimal amount) {
		this.person= person;
		this.amount = amount;
	}

	public Integer getDonationId() {
		return this.donationId;
	}

	public void setDonationId(Integer donationId) {
		this.donationId = donationId;
	}


	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
