package model;
// default package
// Generated Feb 25, 2015 11:58:03 AM by Hibernate Tools 4.3.1

/**
 * SalesByFilmCategory generated by hbm2java
 */
public class SalesByFilmCategory implements java.io.Serializable {

	private SalesByFilmCategoryId id;

	public SalesByFilmCategory() {
	}

	public SalesByFilmCategory(SalesByFilmCategoryId id) {
		this.id = id;
	}

	public SalesByFilmCategoryId getId() {
		return this.id;
	}

	public void setId(SalesByFilmCategoryId id) {
		this.id = id;
	}

}
