package backup;

import java.util.HashSet;
import java.util.Set;

// default package
// Generated Feb 25, 2015 11:58:03 AM by Hibernate Tools 4.3.1

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer id;
	private String name;
	private String country;
	private Set<Donation> donation = new HashSet<Donation>(0);

	public Set<Donation> getDonation() {
		return donation;
	}

	public void setDonation(Set<Donation> donation) {
		this.donation = donation;
	}

	public Person() {
	}

	public Person(String name) {
		this.name = name;
	}

	public Person(String name, String country) {
		this.name = name;
		this.country = country;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
